module.exports = Object.freeze({
    MISSING_PARAMETER: 'MISSING_PARAMETER',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
    USER_CONNECTED: 'USER_CONNECTED',
    USER_CREATED: 'USER_CREATED',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
    ACCESS_DENIED: 'ACCESS_DENIED'
});